before_script:
  - (gem list bundler | grep bundler) || gem install bundler
  - bundle install
  
  - git remote set-url origin git@gitlab.cleevio.cz:$CI_PROJECT_PATH.git
  - git config --global user.email 'dev.ios@cleevio.cz'
  - git config --global user.name 'Mac mini CI'

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

stages:
  - lint
  - test
  - deploy

lint:
  stage: lint
  script:
    - bundle exec fastlane lint
  only:
    - branches
  except:
    - tags
  tags: [ios]
  artifacts:
    paths:
      - fastlane/swiftlint.html
    expire_in: 2 days
  allow_failure: false

test:
  stage: test
  script:
    - bundle exec fastlane test
  only:
    - branches
  except:
    - tags
  tags: [ios]
  allow_failure: false

deploy_beta:
  stage: deploy
  script:
    - bundle exec fastlane deploy_devel
  only:
    - devel
  except:
    - tags
  tags: [ios]
  allow_failure: false

deploy_staging:
  stage: deploy
  only:
    - staging
  script:
    - bundle exec fastlane deploy_staging
  when: manual
  tags: [ios]
  allow_failure: false

deploy_AppStore:
  stage: deploy
  only:
    - master
  script:
    - bundle exec fastlane deploy_appstore
  when: manual
  tags: [ios]
  allow_failure: false

deploy_beta_manual:
  stage: deploy
  except:
    - master
    - devel
  script:
    - bundle exec fastlane deploy_devel
  when: manual
  tags: [ios]
  allow_failure: false

