default_platform(:ios)

platform :ios do

	# ***************************************************** #
	# ******************** DEFINITIONS ******************** #
	# ***************************************************** #

	debug_identifier = "com.tmp.vexl"
	devel_identifier = "com.tmp.vexl.devel"
	staging_identifier = "com.tmp.vexl.staging"
    appstore_identifier = "com.tmp.vexl.appstore"
    xcodeproj_identifier = "vexl.xcodeproj"

	main_scheme = "vexl"
	gsp_path_devel = "vexl/Resources/GoogleServices/Devel/GoogleService-Info.plist"
	gsp_path_staging = "vexl/Resources/GoogleServices/Staging/GoogleService-Info.plist"
	gsp_path_appstore = "vexl/Resources/GoogleServices/AppStore/GoogleService-Info.plist"
	firebase_app_id_devel = "1:386907112085:ios:d4eb7c5afaefc79e50d19c"
	firebase_app_id_staging = "1:386907112085:ios:c4f9a9b9df3c50ce50d19c"
	firebase_app_id_appstore = "1:386907112085:ios:388bfa4f7b872e4650d19c"
	firebase_tester_group_id = "FIXME"
	firebase_cli_path = "/usr/local/bin/firebase"
	slackUrl = "https://hooks.slack.com/services/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"

	# ***************************************************** #
	# ******************** BEFORE ALL ********************* #
	# ***************************************************** #

	ensure_env_vars(
		env_vars: [
			'FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD',
			'FASTLANE_DONT_STORE_PASSWORD', 
			'FASTLANE_USER', 
			'FASTLANE_PASSWORD', 
			'MATCH_KEYCHAIN_PASSWORD',
			'MATCH_PASSWORD'
		]
	) 

	# ***************************************************** #
	# ******************** FUNCTIONS ********************** #
	# ***************************************************** #

	def install_pods
		cocoapods(
			podfile: "Podfile",
			try_repo_update_on_error: true
		)
	end

	# ***************************************************** #
	# ******************** LANE: Lint ********************* #
	# ***************************************************** #

	desc "Swiftlint script for syntax control"
	lane :lint do
		swiftlint(
			reporter: "html",
			output_file: "fastlane/swiftlint.html"
		)
	end

	# ***************************************************** #
	# ******************** LANE: Test ********************* #
	# ***************************************************** #

	desc "Build the app and run tests"
	lane :test do
		install_pods()
		clear_derived_data
		scan(
			scheme: main_scheme,
			output_directory: "fastlane/tests"
		)
	end

	# ***************************************************** #
	# ************** LANE: Certificates setup ************* #
	# ***************************************************** #

	desc "Create certificates and provisioning profiles for every app environment. This should be run once at the beginning of the project"
	lane :create_signing_assets do
		match(
			git_branch: main_scheme,
			type: "development",
			app_identifier: debug_identifier,
			readonly: true  # TODO: remove this line once we have a app store access
		)

		match(
			git_branch: main_scheme,
			type: "adhoc",
			app_identifier: devel_identifier,
			readonly: true  # TODO: remove this line once we have a app store access
		)
	end

	# ***************************************************** #
	# *************** LANE: Deploy beta ******************* #
	# ***************************************************** #

	desc "Submit a new build to Firebase"
	lane :deploy_devel do
		install_pods()

		version = get_version_number
		build = increment_build_number(
			build_number: ENV['CI_JOBENV_ID'],
			xcodeproj: xcodeproj_identifier
		)

		clean_build_artifacts

		commit_version_bump(
			message: "[ci skip] Build version Bump: #{version}(#{build})",
			xcodeproj: xcodeproj_identifier
		)
	
		branch = git_branch
		push_to_git_remote(
			remote: "origin",
			local_branch: "HEAD",
			remote_branch: branch,
			force: false,
			tags: true
		)

		match(
			type: "adhoc",
			git_branch: main_scheme,
			app_identifier: devel_identifier,
			readonly: true # TODO: change to `readonly: is_ci` once we have a app store access
		)

		clear_derived_data

		ipa_path = gym(
			scheme: "#{main_scheme} Devel",
			silent: true,
			clean: true,
			export_method: "ad-hoc",
			export_options: {
				manageAppVersionAndBuildNumber: false,
				compileBitcode: false
			}
		)

		changelog = "\#\##{version}(#{build})"
		changelog += "\n"
		changelog += File.read("./Changelog.txt")

		firebase_app_distribution(
			app: firebase_app_id_devel,
			release_notes: changelog,
			firebase_cli_path: firebase_cli_path,
			ipa_path: ipa_path
		)

		upload_symbols_to_crashlytics(
			gsp_path: gsp_path_beta
		)

		slack(
			username: "Siri",
			payload: {
			   "Build Date" => Time.new.to_s,
			},
			message: "New iOS Firebase devel version released! :tada:",
			slack_url: slackUrl,
			default_payloads: [:test_result],
			attachment_properties: {
				  fields: [{
						title: "Changelog",
						value: changelog,
						short: true	
			   }]
			}
		  )
	end

	# ***************************************************** #
	# ************ LANE: Increment Version **************** #
	# In order to use this you need to send one of these variables:
	# VERSION: Please use semantic versioning (e.g 2.0.1)
	# BUMP_TYPE: It accepts one of these cases:
	#   - major
	#   - minor
	#   - patch
	# ***************************************************** #

	desc "Let you increment the version number before submitting to Appstore"
	lane :bump_version do |options|
		UI.message "Options received: #{options}"

		version = options[:version] ||= ""
		bumpType = options[:bump_type] ||= ""
		hasVersion = !(version.empty?)
		hasBumpType = !(bumpType.empty?)

		if hasVersion
			UI.success "Using version with value '#{version}'"
			increment_version_number_in_xcodeproj(
				version_number: version,
				target: "#{main_scheme}"
			)
		elsif hasBumpType
			UI.success "Using bump_type with value '#{bumpType}'"
			increment_version_number_in_xcodeproj(
				bump_type: bumpType,
				target: "#{main_scheme}"
			)
		else
			UI.success "No parameter for incrementing version was found in the pipeline. Continuing..."
			next
		end

		if hasVersion or hasBumpType
			version = get_version_number
			build = get_build_number(
				xcodeproj: ENV['XCODE_PROJECT']
			)

			clean_build_artifacts

			commit_version_bump(
				message: "[ci skip] Build version Bump: #{version}(#{build})",
				xcodeproj: ENV['XCODE_PROJECT']
			)
			add_git_tag(tag: "#{version}(#{build})")

			branch = git_branch
			push_to_git_remote(
				remote: "origin",
				local_branch: "HEAD",
				remote_branch: branch,
				force: false,
				tags: true
			)
		end
	end
end